# Generated by Django 6.0.2 on 2026-02-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.BigIntegerField(db_index=True)),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField(db_index=True)),
                ('total_luggage_capacity', models.IntegerField()),
                ('available_luggage_capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('SEARCHING', 'SEARCHING'), ('FULL', 'FULL'), ('STARTED', 'STARTED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='SEARCHING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_seats'], name='rides_ride_status_02a957_idx')],
            },
        ),
    ]
