# Generated by Django 6.0.2 on 2026-02-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ride',
            name='rides_ride_status_02a957_idx',
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'available_seats', 'available_luggage_capacity'], name='rides_ride_status_4bd38e_idx'),
        ),
    ]
